# Generated by Django 5.0.2 on 2024-02-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_prices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='model_price',
            new_name='modal_price',
        ),
    ]
